; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = esp32_marauder

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-DENABLE_GIT_VERSION
	-Iesp32_marauder/libraries
	-Iesp32_marauder/libraries/LinkedList
	-Ilibraries
	-Wl,--allow-multiple-definition
board_build.partitions = min_spiffs.csv
lib_ldf_mode = deep+
lib_deps = 
	https://github.com/stevemarple/MicroNMEA.git#master
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/plerup/espsoftwareserial.git
	https://github.com/ivanseidel/LinkedList.git
	bblanchon/ArduinoJson@^6.21.0
	h2zero/NimBLE-Arduino@1.4.1
	adafruit/Adafruit MAX1704X@^1.0.3
	marian-craciunescu/ESP32Ping@^1.7.0
	adafruit/Adafruit NeoPixel@^1.12.0
lib_ignore = 
	TFT_eSPI
    ; Adafruit_NeoPixel
	lv_arduino
	JPEGDecoder
	SwitchLib
	AsyncTCP_RP2040W

[env:esp32s3-debug]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-DENABLE_GIT_VERSION
	-g
	-O0
	-Iesp32_marauder/libraries
	-Iesp32_marauder/libraries/LinkedList
	-Ilibraries
lib_ldf_mode = deep+
lib_deps = 
	https://github.com/stevemarple/MicroNMEA.git#master
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/plerup/espsoftwareserial.git
	https://github.com/ivanseidel/LinkedList.git
	bblanchon/ArduinoJson@^6.21.0
	h2zero/NimBLE-Arduino@^2.3.7
	adafruit/Adafruit MAX1704X@^1.0.3
	marian-craciunescu/ESP32Ping@^1.7.0
lib_ignore = 
	TFT_eSPI
	Adafruit_NeoPixel
	lv_arduino
	JPEGDecoder
	SwitchLib
